# Generated by Django 5.1.2 on 2024-11-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfoundid',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lostfoundid',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lostfoundid',
            name='id_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
