# Generated by Django 5.1.2 on 2024-11-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0002_lostfoundid_email_lostfoundid_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfoundid',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lostfoundid',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='lostfoundid',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lostfoundid',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
