# Generated by Django 5.1.2 on 2025-02-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0003_lostfoundid_latitude_lostfoundid_longitude_and_more'),
    ]

    operations = [
    ]
